import os

TWITTER_APP_KEY = os.environ['TWITTER_APP_KEY']
TWITTER_APP_SECRET = os.environ['TWITTER_APP_SECRET']
TWITTER_KEY = os.environ['TWITTER_KEY']
TWITTER_SECRET = os.environ['TWITTER_SECRET']
PROJECT_NAME = os.environ['PROJECT_NAME']
PUBSUB_TOPIC_NAME = os.environ['PUBSUB_TOPIC_NAME']
SUBSCRIPTION_NAME = os.environ['SUBSCRIPTION_NAME']
