spring:
    main:
        lazy-initialization: true
        web-application-type: none
    
    profiles:
        active: test

    rsocket:
        server:
            port: 7000
            transport: websocket
            
